name: ui-roisummary
rundeckPluginVersion: 1.2
author: Eric Chapman
url: https://github.com/echapmanFromBunnings/ui-roi-summary
date: 2024-01-15T19:50:16.097Z
version: 0.0.1
providers:
    - name: ui-roisummary
      service: UI
      plugin-type: ui
      title: "ROI Summary"
      description: "Job List with ROI Summary View"
      ui:
        - pages: '*'
          scripts:
            - js/init.js
            - js/joblist.js
          styles:
            - css/joblist.css