name: ui-roi-summary
display: Job List ROI Summary View
rundeckPluginVersion: 2.0
author: Eric Chapman
description: Table list view of Jobs with statistics
rundeckCompatibilityVersion: 3.x
targetHostCompatibility: unix
license: Apache 2.0
sourceLink: https://github.com/echapmanFromBunnings/ui-roi-summary
docsLink: https://github.com/echapmanFromBunnings/ui-roi-summary
tags:
    - script
    - UI
date: 2024-01-15T19:50:16.097Z
version: 0.0.1
providers:
    - name: ui-roisummary
      service: UI
      plugin-type: ui
      title: ui-roisummary
      description: Table list view of Jobs with ROI data
      ui:
        - pages: '*'
          scripts:
            - js/init.js
            - js/joblist.js
          styles:
            - css/joblist.css